//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RansomwareBlaster.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>txt</string>
  <string>doc</string>
  <string>docx</string>
  <string>xls </string>
  <string>xlsx</string>
  <string>ppt</string>
  <string>pptx</string>
  <string>pdf</string>
  <string>png</string>
  <string>jpg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExtensionsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExtensionsList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Program Files</string>
  <string>C:\Program Files (x86)</string>
  <string>C:\Windows</string>
  <string>C:\$Recycle.Bin</string>
  <string>C:\System Volume Information</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IgnoreDirectory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IgnoreDirectory"]));
            }
        }
    }
}
